### ISSUE TITLE
Parse checksum fails with checksum_raw not declared

### ISSUE THREAD

**Issue by davegec** [gecio/ansible-image-uploader#20]
## Problem:

Parse checksum fails

```yaml
TASK [image_uploader : Parse checksum] *****************************************
task path: /root/.ansible/roles/image_uploader/tasks/check_for_updates.yml:21
fatal: [localhost]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'checksum_raw'
  
    The error appears to be in '/root/.ansible/roles/image_uploader/tasks/check_for_updates.yml': line 21, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Parse checksum
      ^ here
```

It seems there is a problem when the variable `checksum_raw` is not declared in the images/`{{ image_name }}`.yml

## Fix 

Could declare `checksum_raw` in every `{{ image }}`.yml with value `null`
